### ISSUE TITLE
Can I configure by appsettiongs?

### ISSUE THREAD

**Issue by regis-ranniere** [serilog/serilog-sinks-map#12]
How do I configure the map through the appsettings?

**Comment by nblumhardt** [comment]
This isn't supported at present; the design of this sink revolves around a function mapping from keys to sinks, which isn't a great fit for appsettings. Reading individual values from appsettings (file paths/urls etc.) and then using them in code to configure the map, is the way to go, currently.

**Comment by eklnc** [comment]
I need this feature too.

**Comment by nblumhardt** [comment]
Hi! It should be possible for someone to adapt this via _Serilog.Filters.Expressions_, though it's non-trivial and not something the maintainers are planning at present. If anyone does give it a shot, it would be great to hear how it goes.
