### ISSUE TITLE
docs: Add cleanup policy overview

### ISSUE THREAD

**Issue by julealgon** [serilog/serilog-sinks-map#14]
The main documentation for this sink does not properly explain how the sinks are cleaned up once the limit is reached. I spent some time looking at the code to see how it was disposing the sinks because this was important to my application from a performance standpoint.

Can we add more information related to the cleanup process:

- Is the process deterministic?
- In what order are sinks disposed once the limit is reached? 
- Does the cleanup happen asynchronously, or synchronously?
- When exactly cleanup attempts are made? Before or after the next event is logged?

Having this information upfront would've saved me a few hours of testing and investigation, so I believe this could prove useful for other folks as well.

**Comment by nblumhardt** [comment]
Hi Juliano,

Thanks for investigating! Yes, this documentation would be useful/welcome, thanks 👍

**Comment by nblumhardt** [comment]
Closing this one as stale; doc contributions still welcome if anyone's interested in picking it up.
