### ISSUE TITLE
MappedSink.Dispose doesn't dispose underlying sinks

### ISSUE THREAD

**Issue by dmitry-84** [serilog/serilog-sinks-map#16]
MappedSink.Dispose doesn't dispose underlying sinks.\

Following test fails
```
[Fact]
public void SinksAreDisposedWithMapSinkDispose()
{
    var a = Some.LogEvent("Hello, {Name}!", "Alice");

    var sink = new DisposeTrackingSink();
    using (var log = new LoggerConfiguration()
        .WriteTo.Map("Name", (name, wt) => wt.Sink(sink))
        .CreateLogger())
    {
        log.Write(a);
    }

    Assert.True(sink.IsDisposed);
}
```

**Comment by dmitry-84** [comment]
Possible fix could be moving [`_sinkMap.Clear();`](https://github.com/serilog/serilog-sinks-map/blob/master/src/Serilog.Sinks.Map/Sinks/Map/MappedSink%601.cs#L139) after `foreach`

**Comment by nblumhardt** [comment]
Nasty! Nice spotting, thanks @dmitry-84

**Comment by dmitry-84** [comment]
@nblumhardt thanks for the quick fix.
Do you have ETA of a release?
Thank you.

**Comment by nblumhardt** [comment]
Done, thanks - 1.0.1 should be visible on NuGet soon.
