### ISSUE TITLE
Getting started example not working

### ISSUE THREAD

**Issue by cirrusone** [serilog/serilog-sinks-map#19]
Hello,

I'm trying to re-create the example in the README.md 

```
///Install-Package Serilog.Sinks.Map -Pre
Log.Logger = new LoggerConfiguration()
    .WriteTo.Map("Name", "Other", (name, wt) => wt.File($"./logs/log-{name}.txt"))
    .CreateLogger();
```

It gives error

Error	CS1061	'LoggerSinkConfiguration' does not contain a definition for 'File' and no accessible extension method 'File' accepting a first argument of type 'LoggerSinkConfiguration' could be found (are you missing a using directive or an assembly reference?)

Nuget installed the following
Successfully installed 'Serilog 2.8.0' to netcore ConsoleApp
Successfully installed 'Serilog.Sinks.Map 1.0.1' to netcore ConsoleApp
Successfully installed 'System.Collections.NonGeneric 4.3.0' to netcore ConsoleApp
Executing nuget actions took 630.19 ms

How do I get this to work? The tests also do not appear to have this same example.

**Update:** It also requires a further dependency on Serilog.Sinks.File 4.1.0

**Comment by nblumhardt** [comment]
Thanks for the update 👍
