### ISSUE TITLE
LogFile name for each assembly

### ISSUE THREAD

**Issue by marcofacchetti** [serilog/serilog-sinks-map#20]
Hi, I have a project with a HostBuilder and more different class libraries.
Is it possible for each class library to write the registration into a separate file?
How can I configure appsettings.json or LoggerConfiguration to do it?

**Comment by nblumhardt** [comment]
Hi Marco, thanks for getting in touch. This might be too broad to address here as an issue - if you still need some help with it, tagging your question with `serilog` on StackOverflow will get the most eyes onto it. HTH!
