### ISSUE TITLE
Memory leak when 'sinkMapCountLimit' is set in WriteTo.Map

### ISSUE THREAD

**Issue by LachlanCoote** [serilog/serilog-sinks-map#24]
**Description**
When sinkMapCountLimit is set lower than the possible amount of sinks being created, evicted sinks are still being referenced by LoggerConfiguration's _logEventSinks. The GC is unable to reclaim the resources of those sinks.

**Reproduction**
```
private const int FILE_COUNT = 5;

private static readonly Random _random = new Random();

private static readonly string _path = System.IO.Path.Combine(Environment.GetFolderPath(
	Environment.SpecialFolder.CommonApplicationData), "Serilog-Memleak-Test");

static async Task Main(string[] args)
{
	Log.Logger = new LoggerConfiguration()
		.WriteTo.Map("Number", "",
			     (number, wt) => wt.File($"{_path}/logs-{number}.txt"),
			     sinkMapCountLimit: FILE_COUNT - 1)
		.CreateLogger();

	do
	{
		while (!Console.KeyAvailable)
		{
			Log.Information("Test log entry for {Number}", _random.Next(0, FILE_COUNT).ToString());
			await Task.Delay(100).ConfigureAwait(false);
		}
	} while (Console.ReadKey(true).Key != ConsoleKey.Escape);
}
```

**Expected behavior**
When a wrapped sink is evicted from MappedSink, its resources are reclaimed by the GC.

**Relevant package, tooling and runtime versions**
<table>
  <tr>
    <td>First Discovered</td>
    <td>Reproduced</td>
  </tr>
  <tr>
    <td>.NET Framework 4.6.1</td>
    <td>.NET Core 3.1</td>
  </tr>
  <tr>
    <td>Serilog v2.9.0</td>
    <td>Serilog v2.10.0</td>
  </tr>
  <tr>
    <td>Sinks.Map v1.0.0</td>
    <td>Sinks.Map v1.0.1</td>
  </tr>
  <tr>
    <td>Sink.File v4.1.0</td>
    <td>Sinks.File v4.1.0</td>
  </tr>
</table>

**Comment by nblumhardt** [comment]
Nice spotting - thanks! PR on its way.
