### ISSUE TITLE
System.OutOfMemoryException with Serilog.Sinks.Map

### ISSUE THREAD

**Issue by seayxu** [serilog/serilog-sinks-map#26]
**Description**
The memory keeps growing until the memory is exhausted,memory is not released causing memory leaks.

**Reproduction**
see [demo](https://github.com/seayxu/SerilogMapToFileConsoleApp1)

**Expected behavior**
System.OutOfMemoryException

**Comment by nblumhardt** [comment]
Thank you - this was found and fixed recently, (#24, #25) but not yet published. New version 1.0.2 on the way now #27 .
