### ISSUE TITLE
Combined with dynamic creating SQL tables inside a transaction delivers EF distributed transaction error

### ISSUE THREAD

**Issue by projectje** [serilog/serilog-sinks-map#30]
- When you create dynamic tables in the database based on a log tag
- And a table is not yet existing
- And a TRANSACTION is started 
- And you then log inside that transaction

You will run into "distributed transactions not supported"

E.g.: 

 .WriteTo.Map("Tag", configuration["Serilog:Sql:DefaultTable"], (name, wt) => wt.MSSqlServer(
                    connectionString: configuration.GetConnectionString(configuration["Serilog:Sql:ConnectionStringName"]),
                    sinkOptions: new Serilog.Sinks.MSSqlServer.MSSqlServerSinkOptions
                    {
                        TableName = configuration["Serilog:Sql:Table"] + name,
                        SchemaName = configuration["Serilog:Sql:Schema"],
                        BatchPeriod = new TimeSpan(0, 0, 5),
                        AutoCreateSqlTable = true,
                        BatchPostingLimit = 50,
                        EagerlyEmitFirstEvent = true
                    },
                    columnOptions: SeriLogColumns()
                    ))
                    
                    
A workaround is logical: create all possible log tables that are touched during a transaction before-hand. 
But this will require to mimic the exact same schema as the columns definition used in the Serilog Sql Server configuration which does it automagically. So the easiest is to check if a table exists, if not , write an error to it, then delete the error, so the table is created assuming the highest level someone would set is error.

**Comment by bartelink** [comment]
I don't have permissions to transfer this the SQL repo, and I don't see how this issue can be resolved by changing or adding features in the Map sink, so closing.

If you or anyone can see a way for the Map Sink to help in some way, open to ideas

If something that makes sense and is implementable, then even having a well-thought-out feature request in the issues list here would be of use.
