### ISSUE TITLE
Question: Is there a reason why this package is still Preview?

### ISSUE THREAD

**Issue by hasancemcerit** [serilog/serilog-sinks-map#9]
Could anybody have an update on when we can expect 1.0 released?

**Comment by nblumhardt** [comment]
Hi! Thanks for the nudge.

I think I made some API changes just before opening the release PR (#4) that I was unsure of in hindsight, and so I need some time to go back and reexamine it before committing to a "1.0".

I'm still completely happy with the overall goal of the package, though, and looking forward to working on it again, so I'll hopefully find a chance to look over it again next week :-)

Best regards,
Nick

**Comment by hasancemcerit** [comment]
Thanks for the quick update @nblumhardt :clap:

You are right, it gets the job done. My preliminary tests worked like a charm with different files with RollingFile configuration. 

I haven't really tested with many different files, which I'll end up having, but I am hopeful that ```sinkMapCountLimit``` will come to the rescue to limit open file handles.

One future request might be an option to disable logging of ```keyPropertyName```. :bulb:

Thanks for bringing a pluggable logging framework into this world :blush:

I'll look forward of the release.

Best Regards,
Hasan

**Comment by devgibsonsp** [comment]
I am watching this package closely. It is exactly what I need.

**Comment by nblumhardt** [comment]
https://www.nuget.org/packages/Serilog.Sinks.Map/1.0.0

🎉
